### ISSUE TITLE
Any chance for a 1.34.2 version?

### ISSUE THREAD

**Issue by vekien** [Aryetis/AutoPauseStealth#2]
Hello,

I love this addon, i pretty much require it :D for w/e reason my songs lag for a few seconds at the start of a song. No matter the version of BS im using, no matter gfx settings, addons, vanilla, etc. I have lag for some reason.

This addon solved all that in 1.29, is there any chance for it in 1.34.2?

If not np! thanks!!

**Comment by Aryetis** [comment]
Most likely you can use the latest release and keep using it. I'll double check to be sure later today.
I don't think a single update broke this addon. 
Anyways I'll update it and submit it to beatmods soon™ if that helps.

EDIT : confirming it still works. It seems to have trouble determining the headset's framerate tho. Minor issue, I'll check it.

**Comment by Aryetis** [comment]
Numbers are bumped, minor bug is fixed. 
Here's the [0.1.19 release (for 1.36)](https://github.com/Aryetis/AutoPauseStealth/releases/tag/0.1.19).
I'll upload it to beatmods / ModAssistant later on today. It will probably take them some days to approve it.

Please reopen this ticket if there are any issues.

**Comment by vekien** [comment]
You're a champion, thank you so much for this and for being so quick! I appreciate it a lot, I restart songs a lot when trying to do full combos which makes this mod sooo worth it. Thank you!
